### PR TITLE
Fix: add login hook to ext backends

### LINKED ISSUE #5415: Authentication hooks are not called with external backends
## Describe the bug
The authentication hooks (onLogin) are not called when the authentication is performed by an external backend.

## To Reproduce

1. Setup an external backend
2. Add a module that attach an onLogin hook
3. Do the login
4. The attached hook function is never called 

## Expected behavior
The hook function must be called also when the authentication is done from an external backend.

## Your Environment

* Icinga Web 2 version and modules (System - About): 2.12.4
* PHP version used (`php --version`): 7.4.33

### PR DESCRIPTION
**Pull request by gianlucapiccolo**
Fixes #5415

### CODE REVIEW

File: library/Icinga/Authentication/Auth.php [hunk 1]
```diff
@@ -245,7 +246,8 @@ protected function authExternal()
                     if (! $user->hasDomain()) {
                         $user->setDomain(Config::app()->get('authentication', 'default_domain'));
                     }
-                    $this->setAuthenticated($user);
+		    $this->setAuthenticated($user);
+		    AuthenticationHook::triggerLogin($user);
```
Comment (lippserd) [inline library/Icinga/Authentication/Auth.php]: Can you please correct the indentation and add a new line before the `return`?

**Review by lippserd — CHANGES_REQUESTED** [review]

File: library/Icinga/Authentication/Auth.php (hunk 1 above)
Comment (lippserd) [reply library/Icinga/Authentication/Auth.php]: Thanks!

Comment (lippserd) [reply library/Icinga/Authentication/Auth.php]: Ah wait, newline before return is still missing.
