### PR TITLE
Respect limits and sort orders for format requests

### LINKED ISSUE #2967: Limit, page and sort URL parameters ignored if the format parameter is used
When requesting services, hosts and groups in a format other than HTML, the parameters `limit`, `page` and `sort` won't be respected.

## Expected Behavior

If any of the above parameters is given in the URL and the `format` parameter is set to `json`, `csv` or `sql`, the items in the output must be affected accordingly. If the `limit` parameter is not set, we must retain the old behaviour and return all items nonetheless.

## Current Behavior

All of the above parameters are ignored. All versions of Web 2 are affected.

## Possible Solution

Call `ListController::filterQuery()` after the pagination, limit and sort control have been set up but only apply the default limit if the format is HTML.

## Steps to Reproduce (for bugs)

`limit`parameter works for regular output, e.g.
`/icingaweb2/monitoring/list/services?service_problem=1&dir=desc&limit=2&sort=service_severity`

It won't work if `format` parameter is set to `json` for example, e.g.
`/icingaweb2/monitoring/list/services?service_problem=1&dir=desc&limit=2&sort=service_severity&format=json`

### PR DESCRIPTION
**Pull request by nilmerg**
If anyone wants a more sophisticated fix I'll happily refactor our controller mess :grin: 

fixes #2967

### CODE REVIEW

File: modules/monitoring/library/Monitoring/Controller.php [hunk 1]
```diff
@@ -31,22 +31,32 @@ protected function moduleInit()
 
     protected function handleFormatRequest($query)
     {
-        if ($this->_getParam('format') === 'sql') {
-            echo '<pre>'
-                . htmlspecialchars(wordwrap($query->dump()))
-                . '</pre>';
-            exit;
+        if ($this->getRequest()->getHeader('Accept') === 'application/json') {
```
Comment (nilmerg) [inline modules/monitoring/library/Monitoring/Controller.php]: Don't call getHeader multiple times

File: modules/monitoring/library/Monitoring/Controller.php [hunk 2]
```diff
@@ -31,22 +31,32 @@ protected function moduleInit()
...
+            $desiredFormat = 'json';
+        } elseif ($this->getRequest()->getHeader('Accept') === 'text/csv') {
+            $desiredFormat = 'csv';
+        } else {
+            $desiredFormat = strtolower($this->_getParam('format'));
```
Comment (nilmerg) [inline modules/monitoring/library/Monitoring/Controller.php]: Use $this->params instead

File: modules/monitoring/library/Monitoring/Controller.php [hunk 3]
```diff
@@ -31,22 +31,32 @@ protected function moduleInit()
...
         }
-        if ($this->_getParam('format') === 'json'
-            || $this->_request->getHeader('Accept') === 'application/json') {
-            header('Content-type: application/json');
-            echo json_encode($query->getQuery()->fetchAll());
-            exit;
+
+        if ($desiredFormat && $desiredFormat !== 'html' && ! $this->getRequest()->has('limit')) {
```
Comment (nilmerg) [inline modules/monitoring/library/Monitoring/Controller.php]: Use $this->params instead and use 'html' as default when fetching the format parameter above

**Comment by nilmerg** [comment]
@lippserd Refactored as discussed.
