### PR TITLE
Setup: don't require date.timezone

### LINKED ISSUE #3626: It is required that a default timezone has been set using date.timezone
## Expected Behavior

I don't have to set date.timezone as [Icinga Web 2 falls back anyway](https://github.com/Icinga/icingaweb2/blob/9f15bda698952a369a2bcf949842548a60e447ac/library/Icinga/Application/ApplicationBootstrap.php#L624) in the rare case that my browser doesn't provide any TZ offset.

## Current Behavior

I have to configure it every damn time.

## Possible Solution

Replace the error in the setup wizard with a warning.

## Steps to Reproduce (for bugs)

Run the setup wizard as usual.

## Context

Testing something with a fresh IW2.

## Your Environment

The latest bleeding edge hipster stuff from you.

### PR DESCRIPTION
**Pull request by Al2Klimov**
fixes #3626

### CODE REVIEW

File: modules/setup/library/Setup/WebWizard.php [hunk 1]
```diff
@@ -576,6 +576,7 @@ public function getRequirements($skipModules = false)
         )));
 
         $set->add(new PhpConfigRequirement(array(
+            'optional'      => true,
```
Comment (nilmerg) [inline modules/setup/library/Setup/WebWizard.php]: Please only do this for PHP versions lower than 7.0. v5.6 is still affected.

**Comment by nilmerg** [comment]
And please also update the requirement in the installation documentation.

File: modules/setup/library/Setup/WebWizard.php (hunk 1 above)
Comment (Al2Klimov) [reply modules/setup/library/Setup/WebWizard.php]: I've fixed this in #3747. POC module:

```
[root@07b1f18d5654 /]# cat icingaweb2/modules/badtz/application/clicommands/ProofCommand.php
<?php

namespace Icinga\Module\Badtz\Clicommands;

use Icinga\Cli\Command;

class ProofCommand extends Command
{
    public function fallbackAction()
    {
        var_dump(@date_default_timezone_get());
        var_dump(date_default_timezone_get());
    }
}
[root@07b1f18d5654 /]# cat icingaweb2/modules/badtz/application/controllers/ProofController.php
<?php

namespace Icinga\Module\Badtz\Controllers;

use Icinga\Web\Controller;

class ProofController extends Controller
{
    protected $requiresAuthentication = false;

    public function fallbackAction()
    {
        var_dump(@date_default_timezone_get());
        var_dump(date_default_timezone_get());
    }
}
[root@07b1f18d5654 /]# cat icingaweb2/modules/badtz/application/views/scripts/proof/fallback.phtml
[root@07b1f18d5654 /]#
```
