### PR TITLE
Fix: split fpm-uri flag in socket and url flag

### LINKED ISSUE #5249: icingacli setup config webserver --fpm-uri outputs wrong config when using socks
## Describe the bug
icingacli setup config webserver --fpm-uri outputs wrong config when using socks

## To Reproduce
icingacli help setup config webserver apache --enable-fpm --fpm-uri=/run/php/php8.3-fpm.sock

## Expected behavior
SetHandler "proxy:unix:/run/php/php8.3-fpm.sock|fcgi://localhost/"
instead of
SetHandler "proxy:fcgi:///run/php/php8.3-fpm.sock"

It could be easier to have a --fpm-url (why URI, anyway?) and --fpm-sock-path mutually exclusive options to avoid confusion.

## Your Environment
Include as many relevant details about the environment you experienced the problem in
Icinga Web 2  2.12.1    
PHP Version   8.3.6     
MODULE       VERSION   
setup        2.12.1    
director     1.10.2    
graphite     1.2.2     
incubator    0.20.0    
reactbundle  0.9.0    

* Server operating system and version:
Distributor ID:	Ubuntu
Description:	Ubuntu 24.04 LTS
Release:	24.04
Codename:	noble

### PR DESCRIPTION
**Pull request by Jan-Schuppik**
fixes #5249

### CODE REVIEW

File: modules/setup/library/Setup/Webserver/Nginx.php [hunk 1]
```diff
@@ -10,10 +10,16 @@
...
 class Nginx extends Webserver
 {
-    protected $fpmUri = '127.0.0.1:9000';
+    protected $fpmUrl = '127.0.0.1:9000';
 
     protected $enableFpm = true;
 
+    protected function createFpmUri()
+    {
+
```
Comment (nilmerg) [inline modules/setup/library/Setup/Webserver/Nginx.php:19]: no such empty lines pls

**Review by nilmerg — CHANGES_REQUESTED** [review]

File: modules/setup/library/Setup/Webserver.php [hunk 2]
```diff
@@ -208,25 +230,47 @@ public function setEnableFpm($flag)
...
+     * Set the address where to pass requests to FPM
+     *
+     * @param string $uri
      *
-     * @param   string  $uri
+     * @return  $this
+     */
+    public function setFpmUrl($uri)
+    {
+        $this->fpmUrl = (string)$uri;
```
Comment (nilmerg) [inline modules/setup/library/Setup/Webserver.php:251]: A space after casts please `(string) $uri`

File: modules/setup/application/clicommands/ConfigCommand.php [hunk 3]
```diff
@@ -157,18 +165,23 @@ public function webserverAction()
...
         $enableFpm = $this->params->shift('enable-fpm', $webserver->getEnableFpm());
 
-        $fpmUri = trim($this->params->get('fpm-uri', $webserver->getFpmUri()));
-        if (empty($fpmUri)) {
+        $fpmSocketPath = trim($this->params->get('fpm-socket-path', $webserver->getFpmSocketPath()));
+        $fpmUrl = trim($this->params->get('fpm-url', $webserver->getFpmUrl()));
+        if (empty($fpmUrl)) {
+            $fpmUrl = trim($this->params->get('fpm-uri', $webserver->getFpmUrl()));
+        }
+        if (empty($fpmSocketPath) && empty($fpmUrl)) {
```
Comment (nilmerg) [inline modules/setup/application/clicommands/ConfigCommand.php:173]: This should also fail if both are passed.

**Review by nilmerg — CHANGES_REQUESTED** [review]

**Review by nilmerg — APPROVED** [review]
