### PR TITLE
Fix multi modal windows and submit

### LINKED ISSUE #4525: Clicking multiple times on a quick action opens several overlapping modal windows
## Describe the bug
1. Clicking multiple times on a quick action opens several empty overlapping modal windows.
2. Clicking on the submit button multiple times add multiple entries.

## Screenshot
Screenshot 2021-09-01 at 14 49 36

### PR DESCRIPTION
**Pull request by sukhwinder33445**
fix #4525

### CODE REVIEW

**Review by nilmerg — CHANGES_REQUESTED** [review]

File: public/js/icinga/behavior/modal.js [hunk 1]
```diff
@@ -90,6 +93,8 @@
         var _this = event.data.self;
         var $form = $(event.currentTarget).closest('form');
         var $modal = $form.closest('#modal');
+        // otherwise the form is submitted several times by clicking the "Submit" button several times
+        $form.find('input[type=submit]').prop('disabled', true);
```
Comment (nilmerg) [inline public/js/icinga/behavior/modal.js:97]: Please disable all form inputs like [here](https://github.com/Icinga/icingaweb2/blob/master/public/js/icinga/loader.js#L133). It may not just be the submit button that is submitting the form.

File: public/js/icinga/behavior/modal.js [hunk 2]
```diff
@@ -36,6 +36,9 @@
      * @returns {boolean}
      */
     Modal.prototype.onModalToggleClick = function(event) {
+        // Disable pointer events to block further function calls
+        event.currentTarget.style.pointerEvents = 'none';
```
Comment (nilmerg) [inline public/js/icinga/behavior/modal.js:40]: Please move that further below. It's not part of the initialization procedures after all.

File: public/js/icinga/behavior/modal.js [hunk 3]
```diff
@@ -187,6 +192,10 @@
      * @param $modal {jQuery} The modal element
      */
     Modal.prototype.hide = function($modal) {
+        var actionUrl = $modal.find('[action]').attr('action');
+        actionUrl = actionUrl.split('&').slice(0, -1).join(" ");
+        $('a[href="' + actionUrl + '"]').removeAttr("style");
```
Comment (nilmerg) [inline public/js/icinga/behavior/modal.js:197]: Eeh.. I think now it's the time to consider storing a reference to the modal opener temporarily on the instance while the modal is open. There's just a single modal at a time after all.

Also, don't use jQuery to reset the style. You already didn't need it to define it.

**Review by nilmerg — CHANGES_REQUESTED** [review]

File: public/js/icinga/behavior/modal.js [hunk 4]
```diff
@@ -29,6 +29,11 @@
 
     Modal.prototype = new Icinga.EventListener();
 
+    /**
+     * Element that has opened the modal
+     */
+    let modalOpener;
```
Comment (nilmerg) [inline public/js/icinga/behavior/modal.js:35]: That's not an instance property. Also, `let` is ECMA2015 only and we still have to support IE.

File: public/js/icinga/behavior/modal.js [hunk 5]
```diff
@@ -187,6 +199,8 @@
      * @param $modal {jQuery} The modal element
      */
     Modal.prototype.hide = function($modal) {
+        modalOpener.removeAttribute('style');
```
Comment (nilmerg) [inline public/js/icinga/behavior/modal.js:202]: This removes the entire style attribute. You should only reset/remove what you've added. (i.e. `pointerEvents`)

**Review by nilmerg — CHANGES_REQUESTED** [review]

**Review by nilmerg — APPROVED** [review]
