### PR TITLE
UserGroupBackendForm: add button "Validate Configuration"

### LINKED ISSUE #3233: Missing "Validate Configuration" button
## Expected Behavior

Configuration -> Application -> Authentication has "Validate Configuration" button for both the "User Backends" and "User Group Backends".

## Current Behavior

Only backends listed under "User Backends" have the "Validate Configuration" button. User Group Backends should have it too.

## Steps to Reproduce (for bugs)
1. Go to the page /config/userbackend

### PR DESCRIPTION
**Pull request by Al2Klimov**
fixes #3233

### CODE REVIEW

File: application/forms/Config/UserGroup/UserGroupBackendForm.php [hunk 1]
```diff
@@ -190,4 +214,91 @@ public function onRequest()
...
+     *
+     * This will only run any validation if the user pushed the 'backend_validation' button.
+     *
+     * @param   array   $formData
+     *
+     * @return  bool
+     */
+    public function isValidPartial(array $formData)
+    {
+        if (! parent::isValidPartial($formData)) {
```
Comment (nilmerg) [inline application/forms/Config/UserGroup/UserGroupBackendForm.php]: Please remove this call. Unlike for UserBackends it's not required here and results only in annoying validation errors when interacting with autosubmit elements.

File: application/forms/Config/UserGroup/UserGroupBackendForm.php [hunk 2]
```diff
@@ -190,4 +214,91 @@ public function onRequest()
...
+            return false;
+        }
+
+        if ($this->getElement('backend_validation')->isChecked() && parent::isValid($formData)) {
```
Comment (nilmerg) [inline application/forms/Config/UserGroup/UserGroupBackendForm.php]: Once the call to `Form::isValidPartial` is gone, this needs to change. (e.g. with `isset()`)

File: library/Icinga/Authentication/UserGroup/LdapUserGroupBackend.php [hunk 3]
```diff
@@ -846,4 +850,71 @@ public function getActiveDirectoryDefaults()
...
+        } catch (AuthenticationException $e) {
+            if (($previous = $e->getPrevious()) !== null) {
+                $result->error($previous->getMessage());
+            } else {
+                $result->error($e->getMessage());
+            }
+        } catch (Exception $e) {
+            $result->error(sprintf('Unable to validate backend: %s', $e->getMessage()));
+        }
+        return $result;
```
Comment (nilmerg) [inline library/Icinga/Authentication/UserGroup/LdapUserGroupBackend.php]: I guess an empty line doesn't hurt here. ;)
