### PR TITLE
Fix missing global theme check refs #4723

### LINKED ISSUE #4723: Theme Mode switch enabled on theme without dark/light
## Describe the bug
The Theme Mode switch becomes enabled even if the theme does not have dark/light.

## To Reproduce
1. Set a theme globally that does not have dark/light
2. Set the same theme in the user settings

## Expected behavior
The Theme Mode switch should  stay disabled

## Screenshots
image
image

## Your Environment
* Icinga Web 2 version and modules (System - About): 2.10.0
* Web browser used: Firefox 99.0b7
* Icinga 2 version used (`icinga2 --version`): 2.13.2-1
* PHP version used (`php --version`): 8.0.8
* Server operating system and version: Ubuntu 21.10

### PR DESCRIPTION
**Pull request by moreamazingnick**
if  global theme is selected and theme chooser is disabled, ther should be a check on the system default theme which is the selected theme, if there is dark/lightmode support.
fixes #4723

### CODE REVIEW

File: application/forms/PreferenceForm.php [hunk 1]
```diff
@@ -208,8 +208,15 @@ public function createElements(array $formData)
                     )
                 );
             }
+        } else {
+            $globalThemeFile = Config::app()->get('themes', 'default');
+            $themeFile = StyleSheet::getThemeFile($globalThemeFile);
+            $file = $themeFile !== null ? @file_get_contents($themeFile) : false;
+            if ($file && strpos($file, StyleSheet::LIGHT_MODE_IDENTIFIER) === false) {
+                $disabled = ['', 'light', 'system'];
+            }
```
Comment (nilmerg) [inline application/forms/PreferenceForm.php:217]: This is nearly the same as the structure for the user's theme. Please combine both.

```
$theme = global theme or null;
if (user has chosen theme)
    $theme = user chosen theme

if ($theme !== null && $theme !== default theme)
    ...
```

File: application/forms/PreferenceForm.php [hunk 2]
```diff
@@ -208,8 +208,15 @@ public function createElements(array $formData)
...
         }
-
+
```
Comment (nilmerg) [inline application/forms/PreferenceForm.php:219]: Please don't add superfluous whitespace.

**Review by nilmerg — CHANGES_REQUESTED** [review]
Thanks! Left you some comments :)

File: application/forms/PreferenceForm.php [hunk 3]
```diff
@@ -185,7 +185,8 @@ public function createElements(array $formData)
                 false
             );
         }
-
+        $themeFile = null;
+
```
Comment (nilmerg) [inline application/forms/PreferenceForm.php:189]: We require empty lines after closed control structures if any instructions follow. Though, none when starting control structures, so if you flip both lines around I'm fine with it.

File: application/forms/PreferenceForm.php (hunk 2 above)
Comment (nilmerg) [reply application/forms/PreferenceForm.php:215]: I mean the indentation, not the empty line itself, if you've wondered.

Comment (nilmerg) [reply application/forms/PreferenceForm.php:215]: I can still see the indentation: :thinking: 
Screenshot from 2022-03-29 12-45-06

**Review by nilmerg — APPROVED** [review]
Thank you!

File: application/forms/PreferenceForm.php [hunk 4]
```diff
@@ -208,11 +209,16 @@ public function createElements(array $formData)
                     )
                 );
             }
+        } else {
+            $themeFile = StyleSheet::getThemeFile(Config::app()->get('themes', 'default'));
```
Comment (nilmerg) [inline application/forms/PreferenceForm.php:213]: Hm, I was too fast. This runs only if the user cannot change the theme. But that shouldn't affect the mode selection anyway. Already initialize `$themeFile` with the global default theme. Don't do it here.

**Review by nilmerg — CHANGES_REQUESTED** [review]

File: application/forms/PreferenceForm.php (hunk 4 above)
Comment (moreamazingnick) [reply application/forms/PreferenceForm.php]: I like that even better

**Comment by nilmerg** [comment]
The checks fail, please fix the trailing white-space at line 189.

**Review by nilmerg — APPROVED** [review]
