### PR TITLE
Change FilterMatch to FilterEqual class for single object filter on object name.

### LINKED ISSUE #4682: Wildcard characters in object names should not be processed in detail queries
## Describe the bug
Having an asterisk in an object name causes it to be processed as wildcard.

## To Reproduce
Have a service or host with an asterisk in the name. Click on a link for this object in the UI. The object is not found.

## Expected behavior
The asterisk is not processed as wildcard in this case.

## Additional context
ref/IP/38281

### PR DESCRIPTION
**Pull request by raviks789**
Correspondingly the rendering of the filter for the db query is also modified to identify the instances of FilterEqual and to render accordingly.

This correctly selects the host, service or contact for the detailed view in case the object name contains wild card characters like "\\*".

depends on #4758
fix #4682

### CODE REVIEW

File: library/Icinga/Data/Db/DbQuery.php [hunk 1]
```diff
@@ -222,7 +223,16 @@ protected function renderFilter($filter, $level = 0)
...
             }
         } else {
-            $str .= $this->whereToSql($filter->getColumn(), $filter->getSign(), $filter->getExpression());
+            if ($filter instanceof FilterEqual) {
+                $str .= sprintf(
+                    '%s %s %s',
+                    $filter->getColumn(),
+                    $filter->getSign(),
+                    $this->escapeForSql($filter->getExpression())
+                );
```
Comment (nilmerg) [inline library/Icinga/Data/Db/DbQuery.php:232]: This bypasses not only the wildcard rendering. There's also handling for arrays and the cases for `IS NULL` and `IS NOT NULL` which are lost now.

Since the method is deprecated anyway and (to be) removed by #4758, patch DbConnection::renderFilterExpression instead. There you can differentiate better as well.

**Review by nilmerg — CHANGES_REQUESTED** [review]

File: library/Icinga/Data/Db/DbQuery.php (hunk 1 above)
Comment (raviks789) [reply library/Icinga/Data/Db/DbQuery.php]: Changes made in DbConnection::renderFilterExpression, and the above changes are removed from DbQuery::renderFilter().

File: modules/monitoring/library/Monitoring/DataView/DataView.php [hunk 2]
```diff
@@ -442,7 +443,7 @@ public function applyFilter(Filter $filter)
      */
     public function validateFilterColumns(Filter $filter)
     {
-        if ($filter instanceof FilterMatch) {
+        if ($filter instanceof FilterMatch || $filter instanceof FilterEqual) {
```
Comment (nilmerg) [inline modules/monitoring/library/Monitoring/DataView/DataView.php:446]: Just noticed, this should only check for `FilterExpression`. That's been wrong all these years already.

File: library/Icinga/Data/Db/DbConnection.php [hunk 3]
```diff
@@ -552,7 +554,7 @@ protected function renderFilterExpression(Filter $filter)
             throw new ProgrammingError(
                 'Unable to render array expressions with operators other than equal or not equal'
             );
-        } elseif ($sign === '=' && strpos($value, '*') !== false) {
+        } elseif ($filter instanceof FilterMatch && strpos($value, '*') !== false) {
```
Comment (nilmerg) [inline library/Icinga/Data/Db/DbConnection.php:557]: There's also the check for `!=` below which requires an update.

**Review by nilmerg — CHANGES_REQUESTED** [review]

**Review by nilmerg — APPROVED** [review]

**Review by nilmerg — APPROVED** [review]
Had to adjust some more things as the issue affected also all reference queries (such as comment and downtime queries)

**Review by nilmerg — APPROVED** [review]
