### PR TITLE
Wizard: show LDAP connection settings discovery failure reasons

### LINKED ISSUE #2865: Wizard: LDAP connection settings discovery failure reasons are silented
## Steps to Reproduce (for bugs)

1. Wizard
2. Authentication Type: LDAP
3. LDAP Discovery: lolcat.icinga.com
4. press next

### PR DESCRIPTION
**Pull request by Al2Klimov**
fixes #2865

### CODE REVIEW

File: library/Icinga/Protocol/Ldap/LdapConnection.php [hunk 1]
```diff
@@ -276,6 +285,16 @@ public function discoverySuccessful()
     }
 
     /**
+     * Get {@link discoveryError}
```
Comment (lippserd) [inline library/Icinga/Protocol/Ldap/LdapConnection.php]: Don't link private/protected properties in the public interface doc please.

File: modules/setup/application/forms/LdapDiscoveryPage.php [hunk 2]
```diff
@@ -74,6 +74,8 @@ public function isValid($data)
                 $this->discovery = Discovery::discoverDomain($data['domain']);
                 if ($this->discovery->isSuccess()) {
                     return true;
+                } else {
+                    $this->getElement('domain')->addError($this->discovery->getError()->getMessage());
```
Comment (lippserd) [inline modules/setup/application/forms/LdapDiscoveryPage.php]: The error message should not be bound to the domain field. It should be a form error instead.

**Comment by lippserd** [comment]
LGTM. I hand this over to @nilmerg

File: modules/setup/application/forms/LdapDiscoveryPage.php [hunk 3]
```diff
@@ -74,6 +74,8 @@ public function isValid($data)
                 $this->discovery = Discovery::discoverDomain($data['domain']);
                 if ($this->discovery->isSuccess()) {
                     return true;
+                } else {
+                    $this->addError($this->discovery->getError()->getMessage());
```
Comment (nilmerg) [inline modules/setup/application/forms/LdapDiscoveryPage.php]: Please use Form::error instead since it's ours and generally used in the Wizard. Form::addError is from Zend and may differ in style.
