### PR TITLE
Adjust host severity

### LINKED ISSUE #2926: Wrong order when sorting by host_severity
Related to: https://github.com/Icinga/icingaweb2/issues/2034

The host order by severity should be as follows:

- DOWN (unacknowledged)
- UNREACHABLE (unacknowledged)
- ACKNOWLEDGED (DOWN + UNREACHABLE)
- DOWNTIMES
- UP

### PR DESCRIPTION
**Pull request by theFeu**
fixes #2926

### CODE REVIEW

File: modules/monitoring/library/Monitoring/Backend/Ido/Query/HoststatusQuery.php [hunk 1]
```diff
@@ -117,35 +117,25 @@ class HoststatusQuery extends IdoQuery
...
-                CASE WHEN hs.problem_has_been_acknowledged = 1
-                     THEN 2
-                     ELSE
-                        CASE WHEN hs.scheduled_downtime_depth > 0
-                            THEN 1
-                            ELSE 4
-                        END
-                END
+            'host_severity'                         => 'CASE
+            WHEN hs.current_state = 0
```
Comment (lippserd) [inline modules/monitoring/library/Monitoring/Backend/Ido/Query/HoststatusQuery.php]: You must check the has_been_checked column first before checking anything else. The default value for current_state is 0 anyway.

File: modules/monitoring/library/Monitoring/Backend/Ido/Query/HoststatusQuery.php [hunk 2]
```diff
@@ -117,35 +117,25 @@ class HoststatusQuery extends IdoQuery
...
-                        CASE WHEN hs.scheduled_downtime_depth > 0
-                            THEN 1
-                            ELSE 4
-                        END
+                CASE 
+                WHEN hs.problem_has_been_acknowledged = 1
+                    THEN 8
+                WHEN hs.scheduled_downtime_depth > 0
+                    THEN 4
+                WHEN (NOT hs.problem_has_been_acknowledged = 1) AND (NOT hs.scheduled_downtime_depth > 0)
```
Comment (lippserd) [inline modules/monitoring/library/Monitoring/Backend/Ido/Query/HoststatusQuery.php]: Why not use the CASE..ELSE structure from the previous code? In my opinion its more readable.
