### PR TITLE
Fix: Scheme and hostname prepended to col2 url in the address bar

### LINKED ISSUE #4754: Scheme and hostname prepended to col2 url in the address bar
## Describe the bug
If a filterable Icinga DB Web view is active in the right column and the user adds a filter, `http://localhost` is prepended to the url in the address bar. (`http://localhost/icingaweb2/dashboard#!http://localhost/icingaweb2/icingadb/hosts?host.name_ci=*dummy*`)

## To Reproduce

1. Add the hosts view of Icinga DB Web to the dashboard
2. Go to the dashboard settings
3. Open the hosts view by clicking on the link of the dashlet
4. Add a filter in the hosts view

## Expected behavior
There should be no scheme or hostname prepended. Just like how it is if filtering the same view while it is in the left column.

### PR DESCRIPTION
**Pull request by sukhwinder33445**
Direct access (a.href) automatically prepends the scheme and hostname.

fixes #4754

### CODE REVIEW

**Review by nilmerg — APPROVED** [review]

File: public/js/icinga/loader.js [hunk 1]
```diff
@@ -828,9 +828,7 @@
             if (!! contentSeparator) {
                 var locationQuery = req.getResponseHeader('X-Icinga-Location-Query');
                 if (locationQuery !== null) {
-                    var a = this.icinga.utils.getUrlHelper().cloneNode(true);
-                    a.search = locationQuery ? '?' + locationQuery : '';
-
+                    let url = currentUrl.path + (locationQuery ? '?' + locationQuery : '');
```
Comment (nilmerg) [inline public/js/icinga/loader.js:831]: Woops, wait a moment, `currentUrl` is defined conditionally. While the block below can make use of it pretty fine (it's guarded by the same condition), this isn't. Parse the url yourself, if `currentUrl` isn't defined yet.

**Review by nilmerg — CHANGES_REQUESTED** [review]

File: public/js/icinga/loader.js (hunk 1 above)
Comment (sukhwinder33445) [reply public/js/icinga/loader.js:831]: ohh yes. But isn't it better if I initialize the `currentUrl` just before (out of) the upper if condition? 🤔

Comment (nilmerg) [reply public/js/icinga/loader.js:831]: Then you'd parse it without needing it in case.

Comment (sukhwinder33445) [reply public/js/icinga/loader.js:831]: We need it for the `url` anyway.

**Review by nilmerg — APPROVED** [review]
