### PR TITLE
Fix:Remove detail url when no item selected

### LINKED ISSUE #5053: Detail view url is still present in the browser address bar when the list item is deselected
## Describe the bug
The detail view URL is still present in the browser address bar when the list item is deselected.

## To Reproduce

1. Select a list item (host/service/comment etc)
2. Deselect it by pressing `ctrl + click on item`

### PR DESCRIPTION
**Pull request by sukhwinder33445**
fixes #5053

### CODE REVIEW

File: public/js/icinga/ui.js [hunk 1]
```diff
@@ -37,6 +37,8 @@
         });
     };
 
+    var globalCOl = 'empty';
+
```
Comment (nilmerg) [inline public/js/icinga/ui.js:41]: ??

**Review by nilmerg — CHANGES_REQUESTED** [review]

File: public/js/icinga/loader.js [hunk 2]
```diff
@@ -1057,9 +1056,6 @@
                         'Request to ' + url + ' has been aborted for ',
                         req.$target
                     );
-
-                    // Aborted requests should not be added to browser history
-                    req.addToHistory = false;
```
Comment (nilmerg) [inline public/js/icinga/loader.js:1062]: Manual requests that have been aborted should still be added to history, as discussed yesterday. Though, scripted requests not. So set this to false, but only if `req.scripted`.

**Review by nilmerg — CHANGES_REQUESTED** [review]

**Review by nilmerg — APPROVED** [review]
